# Generated by Django 6.0.7 on 2026-07-24 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0004_emp_user_leaverequest_attendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emp',
            options={'permissions': [('view_dashboard', 'Can view analytics dashboard')]},
        ),
    ]
