# Generated by Django 6.0.7 on 2026-07-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0010_reconcile_role_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='role',
            field=models.CharField(blank=True, choices=[('SOFTWARE_ENGINEER', 'Software Engineer'), ('SENIOR_SOFTWARE_ENGINEER', 'Senior Software Engineer'), ('QA_ENGINEER', 'QA Engineer'), ('DEVOPS_ENGINEER', 'DevOps Engineer'), ('TEAM_LEAD', 'Team Lead'), ('PROJECT_MANAGER', 'Project Manager'), ('HR', 'HR'), ('SYSTEM_ADMINISTRATOR', 'System Administrator')], default='', max_length=30),
        ),
    ]
