# Generated by Django 6.0.7 on 2026-07-24 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0012_clear_invalid_role_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp',
            name='department',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
