# Generated by Django 6.0.7 on 2026-08-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0013_remove_emp_department_delete_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='emp_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
